import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions — FinalBoss",
  description: "The terms governing use of the FinalBoss demo site.",
};

const LAST_UPDATED = "September 8, 2026";

interface Section {
  title: string;
  body: string[];
}

const SECTIONS: Section[] = [
  {
    title: "1. Acceptance of these terms",
    body: [
      "By connecting a wallet, signing up, or otherwise using this site, you agree to these terms. If you don't agree, please don't use the site.",
    ],
  },
  {
    title: "2. What FinalBoss is",
    body: [
      "FinalBoss is a demo trading interface built to showcase a high-leverage perpetuals platform's product design and user experience. It is not a real trading company, broker, or exchange.",
      "No real funds are ever deposited, held, or moved on this site. Order execution, positions, and profit/loss are simulated (\"paper trading\") — placing a trade here never risks or transfers real money.",
      "Market prices shown are either genuinely live (streamed from a public exchange feed) or generated by a local simulator when a live feed is unavailable. Every price panel is labeled LIVE or SIMULATED so you always know which you're looking at — but even LIVE prices exist here for display only and are never used to settle a real trade.",
    ],
  },
  {
    title: "3. Eligibility",
    body: [
      "You must be at least 18 years old to use this site. By using it, you represent that you meet this requirement and that doing so is not prohibited by the laws that apply to you.",
    ],
  },
  {
    title: "4. Accounts & onboarding",
    body: [
      "Connecting a Web3 wallet only reads your public address and balance to display them back to you — this site never requests, stores, or has the ability to move your funds, and never asks for a seed phrase or private key.",
      "Signing up by email does not create a real, server-side account. In this build, the profile you fill out during onboarding (display name, experience level, risk preferences, default leverage) is saved only in your own browser's local storage, and is used only to personalize this demo session. It is never transmitted to us or to any third party.",
      "Because this data lives only in your browser, clearing your browser storage, using a different device, or using private/incognito mode will reset it. Signing out (from the account badge in the navigation bar) also clears it immediately.",
    ],
  },
  {
    title: "5. Simulated trading, no financial advice",
    body: [
      "Nothing on this site — leverage calculators, liquidation-price previews, market data, or any other figure — is financial, investment, tax, or legal advice, and none of it should be relied on to make real trading decisions.",
      "Formulas used for position size, liquidation price, and profit/loss (see the terminal's own calculations) are simplified, illustrative approximations built for a convincing demo, not a production-grade risk engine. They intentionally ignore real-world factors like funding rates, partial liquidations, and exchange fees.",
    ],
  },
  {
    title: "6. Risk disclosure",
    body: [
      "This section expands on the risk notice shown throughout the site: trading perpetual futures with leverage carries a substantial risk of loss and is not suitable for all investors. Leverage up to 1000x can result in the total loss of margin in moments of high volatility.",
      "This applies even though trading on FinalBoss is simulated — the numbers are designed to behave the way a real high-leverage market would, specifically so the risk is felt, not just stated. Treat every liquidation you see here as a preview of what the same leverage would do with real money.",
    ],
  },
  {
    title: "7. Intellectual property",
    body: [
      "The FinalBoss name, logo, and the design, layout, and code of this site are provided for demonstration purposes. Don't represent this site or its content as your own commercial product or as a real, regulated financial service.",
    ],
  },
  {
    title: "8. Disclaimer of warranties & limitation of liability",
    body: [
      "This site is provided \"as is\" and \"as available,\" without warranties of any kind, express or implied — including that it will be uninterrupted, error-free, or that any market data (live or simulated) is accurate at any given moment.",
      "To the fullest extent permitted by law, FinalBoss and its creators aren't liable for any loss or damage arising from your use of this site, including any decision made based on information shown here.",
    ],
  },
  {
    title: "9. Changes to these terms",
    body: [
      "These terms may be updated from time to time as the site changes. The \"last updated\" date at the top of this page reflects the most recent revision. Continuing to use the site after a change means you accept the updated terms.",
    ],
  },
  {
    title: "10. Governing law & contact",
    body: [
      "FinalBoss is a demo project, not a registered business entity, and these terms aren't a binding legal agreement with a real company. They exist to set honest expectations about what this site is and isn't, in the same spirit as the LIVE/SIMULATED badges and risk disclaimers shown elsewhere on the site.",
      "Questions about this site can be directed through the links in the footer.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <span className="font-mono text-xs tracking-wide text-violet-400/70">[ LEGAL ]</span>
      <h1 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">
        Terms &amp; Conditions
      </h1>
      <p className="mt-3 text-sm text-white/40">Last updated: {LAST_UPDATED}</p>

      <p className="mt-8 text-white/70">
        FinalBoss is a demonstration of a high-leverage perpetuals trading interface.
        These terms explain what that means in practice — please read section 2 first,
        since it sets the context for everything else here.
      </p>

      <div className="mt-10 flex flex-col gap-10">
        {SECTIONS.map((section) => (
          <section key={section.title} className="border-t border-white/[0.07] pt-8">
            <h2 className="text-xl font-semibold text-white">{section.title}</h2>
            <div className="mt-3 flex flex-col gap-3">
              {section.body.map((paragraph, index) => (
                <p key={index} className="leading-relaxed text-white/70">
                  {paragraph}
                </p>
              ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
