import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions — FinalBoss",
  description:
    "The terms governing use of FinalBoss, including demo trading and connecting your own exchange account.",
};

const LAST_UPDATED = "September 12, 2026";

interface Section {
  title: string;
  body: string[];
}

const SECTIONS: Section[] = [
  {
    title: "1. Acceptance of these terms",
    body: [
      "By connecting a wallet, signing up, or otherwise using this site, you agree to these terms. If you don't agree, please don't use the site.",
    ],
  },
  {
    title: "2. What FinalBoss is",
    body: [
      "FinalBoss is a trading interface. It is not a broker, an exchange, or a custodian, and it never takes possession of your money. There is nothing to deposit here and nothing to withdraw.",
      "It has two modes, and the terminal always says which one you are in. In Demo mode, order execution, positions, and profit/loss are simulated (\"paper trading\") against demo funds — placing a trade there never risks or transfers real money. In Testnet or Real funds mode, you have connected your own account at a third-party exchange using your own API key, and what you see is that account's real balances and positions, read from the exchange.",
      "Market prices shown are either genuinely live (streamed from a public exchange feed) or generated by a local simulator when a live feed is unavailable. Every price panel is labeled LIVE PRICES or SIMULATED PRICES so you always know which you're looking at. That label is about the price feed only and is deliberately separate from the Demo / Testnet / Real funds control, which is what tells you whose money is involved.",
    ],
  },
  {
    title: "3. Connecting your own exchange account",
    body: [
      "You may connect an API key for your own account at a supported exchange (currently Bybit). Doing so does not give FinalBoss custody of anything: your funds stay in your account at that exchange, subject to that exchange's own terms, and any orders that result execute there and not here.",
      "Keys that carry withdrawal permission are refused at connection time and are never stored. Please create a trade-only key. This is a deliberate limit on the damage any compromise of this site could do — without withdrawal permission, a key cannot move funds off the exchange.",
      "If you choose to save a key, your API secret is encrypted in your own browser under a passphrase you choose (PBKDF2-SHA256, then AES-GCM) and only the resulting ciphertext, its salt and its initialisation vector are stored. The passphrase is never sent to us and we cannot recover it: if you forget it, the saved secret is unrecoverable and you will need to connect the key again. That is a property of the design, not an oversight. You may also choose not to save the key at all, in which case the secret is held in memory for that browser session only.",
      "Your API key identifier (not the secret) is stored in readable form, because it is an identifier rather than a credential and the interface needs it to show you which key is connected before anything is unlocked.",
      "Requests to the exchange are signed in your browser and passed through a relay on this site, which forwards them without being able to read or alter the signed content. A decrypted secret is held only in memory and is cleared when you close the tab, when you sign out, and automatically after a period of inactivity.",
      "At present, connected accounts are read-only in this interface: you can see balances and positions, but orders cannot be placed on them from here. If that changes, this section will change with it.",
    ],
  },
  {
    title: "4. Eligibility",
    body: [
      "You must be at least 18 years old to use this site. By using it, you represent that you meet this requirement and that doing so is not prohibited by the laws that apply to you.",
      "Where you connect your own exchange account, that exchange sets its own eligibility rules, and some exclude residents of particular countries from trading perpetual futures at all. Those rules are between you and them, and meeting them is your responsibility.",
    ],
  },
  {
    title: "5. Accounts & what is stored",
    body: [
      "Signing up by email creates a real account on our backend (Supabase). Your email address and password are handled by that service, and the profile you fill out during onboarding — display name, experience level, risk preferences, default leverage — is stored against that account on a server, not only in your browser. That is what lets your settings and positions follow you to another device.",
      "Stored against your account: your profile, your demo positions and demo funding history, your referral code, and — only if you choose to save one — the encrypted form of an exchange API secret as described in section 3.",
      "Connecting a Web3 wallet only reads your public address and balance to display them back to you. This site never requests, stores, or has the ability to move your funds, and never asks for a seed phrase or private key.",
      "Some things are kept in your browser rather than on a server: your chosen account mode, a dismissed privacy notice, and whether you have seen the walkthrough. Signing out clears the data belonging to your session from this browser, locks any connected exchange key, and ends the server session. Clearing browser storage, using a different device, or using private/incognito mode resets anything held locally.",
      "If a deployment of this site has no backend configured, everything above falls back to browser-only storage and nothing is transmitted anywhere. The settings screen tells you which of the two you are on.",
    ],
  },
  {
    title: "6. Simulated trading, no financial advice",
    body: [
      "Nothing on this site — leverage calculators, liquidation-price previews, market data, or any other figure — is financial, investment, tax, or legal advice, and none of it should be relied on to make real trading decisions.",
      "Formulas used for position size, liquidation price, and profit/loss (see the terminal's own calculations) are simplified, illustrative approximations built for a convincing demo, not a production-grade risk engine. They intentionally ignore real-world factors like funding rates, partial liquidations, and exchange fees.",
      "In particular, the demo engine liquidates a position once roughly 65% of its margin is gone, which puts liquidation about 0.065% from entry at 1000x and 0.130% at 500x — the same percentage on every market. A real venue sets its own maintenance margin, varies it by symbol and position size, and may account for your whole account balance rather than one position's margin. Do not treat a liquidation price shown here as the one your exchange would use.",
    ],
  },
  {
    title: "7. Risk disclosure",
    body: [
      "This section expands on the risk notice shown throughout the site: trading perpetual futures with leverage carries a substantial risk of loss and is not suitable for all investors. Leverage up to 1000x can result in the total loss of margin in moments of high volatility.",
      "At 1000x, a move of about a tenth of a percent against you is the whole of your margin. On a market that routinely moves several percent in a day, that is a matter of seconds, and it is the expected outcome rather than an unlucky one.",
      "This applies even though trading in Demo mode is simulated — the numbers are designed to behave the way a real high-leverage market would, specifically so the risk is felt, not just stated. Treat every liquidation you see here as a preview of what the same leverage would do with real money.",
    ],
  },
  {
    title: "8. Intellectual property",
    body: [
      "The FinalBoss name, logo, and the design, layout, and code of this site are provided for demonstration purposes. Don't represent this site or its content as your own commercial product or as a real, regulated financial service.",
    ],
  },
  {
    title: "9. Disclaimer of warranties & limitation of liability",
    body: [
      "This site is provided \"as is\" and \"as available,\" without warranties of any kind, express or implied — including that it will be uninterrupted, error-free, or that any market data (live or simulated) is accurate at any given moment.",
      "To the fullest extent permitted by law, FinalBoss and its creators aren't liable for any loss or damage arising from your use of this site, including any decision made based on information shown here.",
    ],
  },
  {
    title: "10. Changes to these terms",
    body: [
      "These terms may be updated from time to time as the site changes. The \"last updated\" date at the top of this page reflects the most recent revision. Continuing to use the site after a change means you accept the updated terms.",
    ],
  },
  {
    title: "11. Governing law & contact",
    body: [
      "FinalBoss is a demo project, not a registered business entity, and these terms aren't a binding legal agreement with a real company. They exist to set honest expectations about what this site is and isn't, in the same spirit as the LIVE/SIMULATED badges and risk disclaimers shown elsewhere on the site.",
      "Questions about this site can be directed through the links in the footer.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <span className="font-mono text-xs tracking-wide text-violet-400/70">[ LEGAL ]</span>
      <h1 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">
        Terms &amp; Conditions
      </h1>
      <p className="mt-3 text-sm text-white/40">Last updated: {LAST_UPDATED}</p>

      <p className="mt-8 text-white/70">
        FinalBoss is a high-leverage perpetuals trading interface. It never holds
        your money: you either trade demo funds here, or connect your own account
        at an exchange and trade there. These terms explain what that means in
        practice — read section 2 first, since it sets the context for everything
        else, and section 3 before connecting an API key.
      </p>

      <div className="mt-10 flex flex-col gap-10">
        {SECTIONS.map((section) => (
          <section key={section.title} className="border-t border-white/[0.07] pt-8">
            <h2 className="text-xl font-semibold text-white">{section.title}</h2>
            <div className="mt-3 flex flex-col gap-3">
              {section.body.map((paragraph, index) => (
                <p key={index} className="leading-relaxed text-white/70">
                  {paragraph}
                </p>
              ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
