import type { LucideIcon } from "lucide-react";
import {
  Zap,
  ShieldCheck,
  Layers,
  Gauge,
  Ghost,
  Link2,
  Wallet,
  Users,
  Rocket,
  BadgeDollarSign,
} from "lucide-react";
import type { WalletOption } from "@/types/wallet";
import type { AffiliateTier } from "@/types/affiliate";

export interface NavLink {
  label: string;
  href: string;
}

export const NAV_LINKS: NavLink[] = [
  { label: "Trade", href: "/terminal" },
  { label: "Affiliates", href: "/affiliates" },
  { label: "Sign Up", href: "/signup" },
];

export interface Feature {
  icon: LucideIcon;
  title: string;
  description: string;
}

export const FEATURES: Feature[] = [
  {
    icon: Gauge,
    title: "Up to 1000x Leverage",
    description:
      "Size positions from 1x to 1000x with a single slider. Cross and isolated margin modes built for high-conviction traders.",
  },
  {
    icon: Zap,
    title: "Zero Gas Fees",
    description:
      "Powered by off-chain matching infrastructure inspired by Orderly Network and Aark — trade without paying a cent in gas.",
  },
  {
    icon: Layers,
    title: "Deep Orderbook Liquidity",
    description:
      "A professional-grade central limit orderbook with real-time depth, not an AMM curve — tight spreads at every size.",
  },
  {
    icon: ShieldCheck,
    title: "Battle-Tested Security",
    description:
      "Non-custodial settlement, audited infrastructure, and transparent on-chain proof of reserves.",
  },
  {
    icon: Rocket,
    title: "Instant Settlement",
    description:
      "Orders fill and settle in milliseconds — no waiting on block confirmations to manage your risk.",
  },
  {
    icon: BadgeDollarSign,
    title: "Referral Rewards",
    description:
      "Earn a share of the fees generated by every trader you refer, paid out automatically in real time.",
  },
];

export interface HowItWorksStep {
  step: number;
  title: string;
  description: string;
}

export const HOW_IT_WORKS_STEPS: HowItWorksStep[] = [
  {
    step: 1,
    title: "Connect your wallet",
    description:
      "Link MetaMask, Phantom, or any WalletConnect-compatible wallet in a single click — no sign-up forms required.",
  },
  {
    step: 2,
    title: "Deposit USDC",
    description:
      "Fund your account with USDC. Deposits settle instantly with zero gas fees thanks to our off-chain infrastructure.",
  },
  {
    step: 3,
    title: "Choose your leverage",
    description:
      "Dial in anywhere from 1x to 1000x leverage and go long or short on your favorite perpetual markets.",
  },
  {
    step: 4,
    title: "Trade & manage risk",
    description:
      "Track your positions, PnL, and liquidation price live, and close out whenever you're ready to lock in gains.",
  },
];

export const WALLET_OPTIONS: WalletOption[] = [
  {
    id: "metamask",
    name: "MetaMask",
    description: "Connect using browser wallet",
  },
  {
    id: "phantom",
    name: "Phantom",
    description: "Multi-chain wallet",
  },
  {
    id: "walletconnect",
    name: "WalletConnect",
    description: "Scan with any mobile wallet",
  },
];

export const WALLET_ICONS: Record<string, LucideIcon> = {
  metamask: Wallet,
  phantom: Ghost,
  walletconnect: Link2,
};

export const AFFILIATE_TIERS: AffiliateTier[] = [
  {
    id: "bronze",
    name: "Bronze",
    requirement: "0 – 10 referrals",
    commissionPct: 20,
    perks: ["20% fee-share commission", "Real-time referral dashboard", "Monthly payouts in USDC"],
  },
  {
    id: "silver",
    name: "Silver",
    requirement: "11 – 50 referrals",
    commissionPct: 30,
    perks: ["30% fee-share commission", "Priority support", "Weekly payouts in USDC", "Custom referral codes"],
    recommended: true,
  },
  {
    id: "gold",
    name: "Gold",
    requirement: "51+ referrals",
    commissionPct: 40,
    perks: ["40% fee-share commission", "Dedicated account manager", "Instant payouts in USDC", "Co-marketing opportunities"],
  },
];

export const ASSET_SYMBOL = "BTC-PERP";

export const STATS_SEED = {
  totalVolume: 4_820_000_000,
  activeTraders: 128_400,
  dailyLiquidations: 3_950_000,
};

export const AFFILIATE_STATS_SEED = {
  totalPaidOut: 12_400_000,
  activeAffiliates: 6_230,
  avgCommission: 320,
};

export const ICONS = { Users, Wallet };
