import { Reveal } from "@/components/ui/Reveal";

export function AffiliateHero() {
  return (
    <section className="px-4 pb-12 pt-16 sm:px-6 lg:px-8">
      <Reveal className="mx-auto max-w-3xl text-center">
        <span className="font-mono text-xs tracking-wide text-emerald-400/70">
          [ REFERRAL PROGRAM ]
        </span>
        <h1 className="mx-auto mt-4 max-w-3xl text-4xl font-semibold tracking-tight text-white sm:text-5xl">
          Earn real yield by growing the ecosystem
        </h1>
        <p className="mx-auto mt-5 max-w-2xl text-white/55">
          Share your referral link, and earn a share of the trading fees
          generated by every trader you bring on board — paid automatically,
          forever.
        </p>
      </Reveal>
    </section>
  );
}
